# Generated by Django 5.2.8 on 2025-11-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_solicitudes', '0002_seguimientosolicitud_tiposolicitud_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposolicitud',
            name='responsable',
            field=models.CharField(choices=[('1', 'Control escolar'), ('2', 'Responsable de programa'), ('3', 'Responsable de tutorías'), ('4', 'Director')], default='1', max_length=1),
        ),
    ]
